# -*- coding: utf-8 -*-
"""IA1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nqOVwaMlVfHpG0660TZ7e-iOQl4h0gZP

**Q-1 Commercial Property Management System**
"""

length  = float(input("Enter the length of space in Metres: "))
width   = float(input("Enter the width of the space in Metres: "))
area = length * width

if(area<=100):
  print("This is your area: ", round(area,2),"\nThis is a SMALL sized property")
elif(area<=400):
  print("This is your area: ", round(area,2),"\nThis is a MEDIUM sized property")
else:
  print("This is your area: ", round(area,2),"\nThis is a LARGE property")



"""**Q-2 Integrated Health Management App**"""

weight = float(input("Enter your weight in Kgs: "))
height = float(input("Enter your height in metres: "))

bmi = weight/(height**2)
print("Your current BMI is: ", bmi)
if bmi < 20:
  print("You are underweight. You need to put on weight, so you need to consume more fatty and protein rich food. You need to do weight training.")
elif (bmi >= 20 and bmi < 25):
  print("You are normal weight. Keep doing what you're doing, consume more protein and keep working out by doing cardiovascular and weight training.")
elif (bmi >= 25 and bmi < 30):
  print("You are overweight. You need to lose some weight, so you need to consume more protein rich food and reduce the intake of carbohydrates. You need to do weight training and cardiovascular training.")
elif (bmi >= 30 and bmi < 35):
  print("You are in Obese Class I. You need to lose weight, reduce the intake of carbohydrates. You need to do weight training and cardiovascular training.")
elif (bmi >= 35 and bmi < 40):
  print("You are in Obese Class II. You need to lose a lot of weight, go on a strict ketogenic diet and reduce the intake of carbohydrates. You need to do weight training and cardiovascular training.")
else:
  print("You are Bariatric Obese. You need to consult a doctor.")



"""**Q-3 Educational Record System**"""

def add_records(d,name,values):
    d[name]=values
    return d

def update_records(d,name,values):
  if name in d:
    d[name]=values
  else:
    print(f"The {name} is not in the database")
  return d

def retrieve_record(d,name):
  if name in d:
    return d[name]
  else:
    print(f"The {name} is not in the database")



d={}
while True:
  print("1.Add Record")
  print("2.Update Record")
  print("3.Retrieve Record")
  print("4.Exit")
  choice=input("Enter the Number ")
  if choice=='1':
    name=input("Enter the Name of the student")
    marks=input("Enter the Grades of the student in order")
    print(add_records(d,name,marks))

  elif choice=='2':
    name=input("Enter the Name of the student")
    marks=input("Enter the Grades of the student in order to be updated")
    print(update_records(d,name,marks))
  elif choice =='3':
    name=input("Enter the Name of the student")
    print(retrieve_record(d,name))
  else:
    break



"""**Q-4 Content Recommendation Engine**"""

clist = ['Tom and Jerry', 'My Little Pony', 'Looney Toons', 'Horton', 'Bee', 'Toy Story', 'Life of PI']
tlist = ['Regular Show', 'Adventure Time', 'Gumball']
alist = ['FRIENDS', 'How I Met Your Mother', 'John Wick', 'Brooklyn Nine Nine']
slist = ['Life of Alfred Hitchcock', 'Daily News']
age = int(input("Enter your age: "))

if age < 13:
  print("You're a child. You should try watching these:  \n", clist)
elif (age >= 13 and age < 18):
  print("You're a teenager. You should try watching these:  \n", tlist)
elif (age >= 18 and age < 40):
  print("You're an adult. You should try watching these:  \n", alist)
else:
  print("You're a senior. You should try watching these:  \n", slist)



"""**Q-5 Promotional Email Dispatcher**"""

sub_id = []
even_id = []
n = int(input("Enter the number of Sub IDs you want to enter: "))
for i in range(n):
  sub_id.append(input("Enter the email id: "))
for i in range(n):
  if i % 2 == 0:
    even_id.append(sub_id[i])
print("The list of even numbered subscriber IDs: ",even_id)



"""**Q-6 Corporate Network Security System**"""

while True:
  pwd = input("Enter the correct password to see the secret message or else enter 123 to exit : ")
  secret = "hoohah"
  if pwd == secret.upper():
    print("Here's the secret message: You will have a good life if you keep working hard")
    break
  elif pwd == "123":
    break



"""**Q-7 Customer Feedback**"""

import statistics
fb = []
size = int(input("Enter number of feedbacks: "))
for i in range(size):
  fb.append(int(input("Enter your ratings out of 5 for your experience: ")))
mean_fb = statistics.mean(fb)
if mean_fb < 3:
  print(mean_fb, "is your AVERAGE FEEDBACK SCORE. Bad Experience, need to work a lot on improvement")
elif mean_fb >= 3 and mean_fb < 5:
  print(mean_fb, "is your AVERAGE FEEDBACK SCORE. Decent but could be improved")
else:
  print(mean_fb, "is your AVERAGE FEEDBACK SCORE. Amazing, keep it up")



"""**Q-8 Content Moderation**"""

l=['word','madam','nice','beautiful','wifaounenfiwifn']

for i in l:
  count=0
  for j in range(len(i)):
    if i[j]=='a' or i[j]=='e' or i[j]=='i' or i[j]=='o' or i[j]=='u':
      count=count+1
  if count>5:
    l.remove(i)

print(l)



"""**Q-9 Automated Event Reminder**"""





"""**Q-10 Robust Financial Calculator**"""

name = input("Enter your name: ")
rate = 0.05
try:
  amount = input("Enter your savings amount: ")
  amount_int = float(amount)
except Exception as e:
  print(e)
print("Your savings interest is: ", round(amount_int * rate,2))
print("Your total amount is: ", round(amount_int+(amount_int * rate),2))



"""**Q-11 Polling**"""

name = input("Enter Name: ")
id = int(input("Enter id number: "))
c_name = input("Enter candidate name")
print("Name:", name," of id:", id, " voted for:", c_name)

from decimal import DivisionByZero
## 12
while True:
  op = int(input("Enter 1/2/3/4/5 for Addition, Subtraction, Multiplication, Divison, EXIT"))
  if op == 5:
    break
  elif op == 1:
    x = int(input("Enter first value: "))
    y = int(input("Enter second value: "))
    print(x,"+",y, "=",x+y)
  elif op == 2:
    x = int(input("Enter first value: "))
    y = int(input("Enter second value: "))
    print(x,"-",y, "=",x-y)
  elif op == 3:
    x = int(input("Enter first value: "))
    y = int(input("Enter second value: "))
    print(x,"*",y, "=",x*y)
  else:
    x = int(input("Enter first value: "))
    y = int(input("Enter second value: "))
    try:
      print(x,"/",y, '=', x/y)
    except DivisionByZero as e:
      print(e)
      continue

## 14
with open("path to the file/ file name","r") as file_obj:
  content=file_obj.read()
  print(content)
file_obj.close()

## 15
with open("path to the file/ file name",'w') as  file_obj:
  file_obj.write("company news or stock information or industry news or all")
  print(file_obj.read())
file_obj.close()