# -*- coding: utf-8 -*-
"""Lvadsusr166_MAZIN MOHAMMAD SAYEED.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14jghhxPC7KAUuzXobdCAjUuE6v1MgtSd
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1-a) Loading the dataset
dataset = pd.read_csv(r'/content/Final Dataset - IPL.csv')
df = pd.DataFrame(dataset)
'''
The dataset which was a csv file was loaded using pandas and further converted
into a dataframe using pandas
'''

# 1-b) Basic Information about the dataset
df.info()
'''
Basic information about the dataset like, number of rows and columns, Datatypes
of the various columns and  number of null/ missing values was seen using the
info() function.
'''

# Also 1-b)
print(df.isnull().sum())
'''
Further more we can see there are no null/ missing values
'''

# 2-a) Missing Value Handling
print(df.isnull().sum())
'''
Since we just saw above that there are no missing values, we have no need to
bother about filling or dropping the missing values.
'''

# 2-b) Duplicate Data Entries
print(df.duplicated())
print("Number of non duplicated entries: ",df.duplicated().count())

'''
This shows us that there are no duplicate values in the dataset and we can now
proceed with our analysis
'''

# 3-a) Descriptive Statistics
print(df.describe())

'''
This shows us the descriptive statistics of the numerical columns of the dataset
'''

# 4-a) Data Visualisation: Various graphs and plots are shown below
# Number of matches per venue
dataset.groupby('venue').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))

# first innings scores and their frequency
df['first_ings_score'].plot(kind='hist', bins=20, title='first_ings_score')

# second innings scores and their frequency
df['second_ings_score'].plot(kind='hist', bins=20, title='second_ings_score')

# Heat map of venues and stages
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['stage'].value_counts()
    for x_label, grp in df.groupby('venue')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('venue')
_ = plt.ylabel('stage')

plt.pie(dataset.groupby('match_winner').size(),autopct='%1.1f%%')

# Scatter plot between First Innings Score and Second Innings Score
df.plot(kind='scatter', x='first_ings_score', y='second_ings_score', s=32, alpha=.8)

# 5-a)
# Teams who won the toss, their inning scores and venue can be depicted using
# heat maps and other plots

# 6-a) Outlier Detection
sns.boxplot(x=df['first_ings_wkts'], y=df['second_ings_wkts'])
plt.title('Box Plot')
plt.show()

'''
A box plot between the number of wickets lost during first innings vs the number
of wickets lost during second innings was plotted
'''

sns.boxplot(x=df['first_ings_score'], y=df['second_ings_score'])
plt.title('Box Plot')
plt.show()

'''
A box plot between the teams who batted first vs the teams who batted second was
shown to determine which teams won
'''

# 7-a)
# Line Plot for teams and venues can be plotted to see their performance at different venues

# 8-a) Player Spotlight
# Player of the match and how many times they won it
dataset.groupby('player_of_the_match').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'), figsize = (10,20))
'''
This shows us the players who have won player of the match and how many times
they have won it. Looking at the their names we can say that most of the time
it's the bowlers who have the most player of the match awards and the batsmen
who have won are hard hitters, i.e. they come on to the field with the
intention of hitting the balls hard. Thus, the impact of top scorers and best
bowlers on their teams' success is tremendously huge. Their performance directly
affects the teams chances to win or lose the match
'''

# 9-a) Data Discovery
sns.boxplot(x=df['first_ings_wkts'], y=df['second_ings_wkts'])
plt.title('Box Plot')
plt.show()
dataset.groupby('player_of_the_match').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'), figsize = (10,20))

'''
The given dataset was a Sports Season's dataset which contained records for the
matches played during the given season of IPL. The dataset was loaded with no
issues using the pandas library for Python. After loading the dataset, the
structure and the content of the dataset was checked. The shape, size of the
dataset was taken into account including the number of missing values. Next,
Data Cleaning was performed and it was found that there were not any missing
values, so that was a big positive. Next thing the dataset was checked for was
duplicate values and no duplicate values were found. Descriptive analysis of the
dataset was done to calculate the mean, median, mode, range, variance and
standard deviation of the various numeric columns present in the dataset.
Following this, various charts and plot were made to depict the relationships
between the various data fields, which helped in understanding the data
characteristics and finding trends and anomalies. Further correlation between
match conditions such as the toss decision, innings score and venues and their
impact of the games was also observed and studied. Scatter plot between innings
scores was also plotted. Box plots were used to detect anomalies and outliers.
Teams performance and results at different venues was also depicted and noted.
The players who won player of the matches were shown using a graph and which
person either the batsmen or the bowler was winning more player of the matches,
further the impact of their performance on the team's results was also studied.
'''